### ISSUE TITLE
[BUG] 升级版本时新增菜单报错

### ISSUE THREAD

**Issue by luqin** [hs-web/hsweb-framework#132]
# BUG 说明
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.dongweirj.xproject.XProjectApplication.main(XProjectApplication.java:33)
Caused by: java.lang.RuntimeException: java.sql.SQLException: Field 'menu_id' doesn't have a default value
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.wrapThrowable(JavaAdapterServices.java:285)
	at jdk.nashorn.javaadapters.org_hswebframework_web_starter_init_UpgradeCallBack.execute(Unknown Source)
	at org.hswebframework.web.starter.init.simple.SimpleDependencyUpgrader.lambda$upgrade$2(SimpleDependencyUpgrader.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.hswebframework.web.starter.init.simple.SimpleDependencyUpgrader.upgrade(SimpleDependencyUpgrader.java:64)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$69$7725A$\^eval\_$cu1$restOf.L:1#L:321(<eval>:323)
	at jdk.nashorn.javaadapters.org_hswebframework_web_starter_init_UpgradeCallBack.execute(Unknown Source)
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doUpgrade(SimpleDependencyInstaller.java:60)
	at org.hswebframework.web.starter.init.SystemInitialize.lambda$doInstall$0(SystemInitialize.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:119)
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:199)
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:166)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	... 6 common frames omitted
Caused by: java.sql.SQLException: Field 'menu_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:2843)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1091)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:2841)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:194)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:256)
	at org.hswebframework.ezorm.rdb.executor.AbstractJdbcSqlExecutor.update(AbstractJdbcSqlExecutor.java:279)
	at org.hswebframework.ezorm.rdb.executor.AbstractJdbcSqlExecutor.insert(AbstractJdbcSqlExecutor.java:322)
	at org.hswebframework.ezorm.rdb.executor.AbstractJdbcSqlExecutor$$FastClassBySpringCGLIB$$f94c074f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at org.hswebframework.web.datasource.DefaultJdbcExecutor$$EnhancerBySpringCGLIB$$9f0b0d71.insert(<generated>)
	at org.hswebframework.ezorm.rdb.simple.SimpleInsert.exec(SimpleInsert.java:65)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$75$5964A$\^eval\_$cu1$restOf.L:1#upgrade(<eval>:289)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$70$7838A$\^eval\_.L:1#L:321#L:324(<eval>:325)
	... 25 common frames omitted

```

# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.8
 
# 复现步骤

```
//版本更新信息
var versions = [
  {
    version: '1.2.3',
    upgrade: function(context) {
      var database = context.database;
      var logger = context.logger;

      var taskMenu = {
        'describe': ' ',
        // "icon": "",
        'id': 'task',
        'name': 'abc',
        'parentId': 'project',
        'path': 'sOrB',
        'permissionId': 'user',
        'sortIndex': 15,
        'status': 1,
        'url': '/a/tasks',
      };
      var taskAutzMenu = {
        id: org.hswebframework.web.id.IDGenerator.MD5.generate(),
        parentId: '-1',
        menuId: 'a-task',
        status: 1,
        settingId: '98d74130b3cb06afc0ae8e5b57a6c052',
        path: '-',
      };

      database.getTable('s_menu').createInsert().values([taskMenu]).exec();
      database.getTable('s_autz_menu').createInsert().values([taskAutzMenu]).exec();

      logger.info("增加任务菜单: {}", taskMenu.id);
    },
  },
  {
    version: '1.1.0',
    upgrade: function(context) {
      java.lang.System.out.println(info.comment + ' 更新到1.1.0了');
    },
  },
];

var JDBCType = java.sql.JDBCType;

function install(context) {
  java.lang.System.out.println(info.comment + ' install');

  var database = context.database;
}

function initialize(context) {
  var database = context.database;
  database.getTable('s_menu').createInsert().values(menus).exec();
  database.getTable('s_autz_setting').createInsert().values(autz_setting).exec();
  database.getTable('s_autz_menu').createInsert().values(autz_menu).exec();
  database.getTable('s_user').createInsert().values(user).exec();
}

//设置依赖
dependency.setup(info)
  .onInstall(install)
  .onUpgrade(function(context) { //更新时执行
    var upgrader = context.upgrader;
    upgrader.filter(versions)
      .upgrade(function(newVer) {
        newVer.upgrade(context);
      });
  })
  .onUninstall(function(context) { //卸载时执行

  }).onInitialize(initialize);
```

# 期望结果
此功能期望的执行结果

# 截图说明

**Comment by zhou-hao** [comment]
请升级hsweb版本到3.0.8 试试

**Comment by luqin** [comment]
当前版本已经是 3.0.8

**Comment by zhou-hao** [comment]
升级的时候，把属性名改成数据库列名，比如 `menuId => menu_id` , `id => u_id`.
