### ISSUE TITLE
删除文件带有缓存的记录时会报错[BUG]

### ISSUE THREAD

**Issue by hl0071** [hs-web/hsweb-framework#136]
# BUG 说明

删除文件带有缓存的记录时会报错，比如file，可能是因为deletebypk是有查询了select所致吧，
记录删除成功，不影响使用就是会报一个错误。fileinfoservice带有@Cacheable
`org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method selectByPk(java.lang.String) on null context object
	at org.springframework.expression.spel.ast.MethodReference.throwIfNotNullSafe(MethodReference.java:149)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:100)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:90)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:57)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.OpPlus.getValueInternal(OpPlus.java:85)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:119)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:257)
	at org.springframework.cache.interceptor.CacheOperationExpressionEvaluator.key(CacheOperationExpressionEvaluator.java:117)
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.generateKey(CacheAspectSupport.java:741)
	at org.springframework.cache.interceptor.CacheAspectSupport.performCacheEvict(CacheAspectSupport.java:473)
	at org.springframework.cache.interceptor.CacheAspectSupport.processCacheEvicts(CacheAspectSupport.java:459)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:417)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:323)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at org.hswebframework.web.service.file.simple.SimpleFileInfoService$$EnhancerBySpringCGLIB$$b972c6a7.deleteByPk(<generated>)
	at cotron.admin.web.asset.manage.control.UploadFileControl.delwithfile(UploadFileControl.java:91)`

# 运行环境
java: 1.8.0_131
maven: 3.3.9
hsweb: 3.0.8
 
# 复现步骤

# 期望结果
此功能期望的执行结果

# 截图说明

**Comment by zhou-hao** [comment]
感谢提交，3.0.9 将修复此问题
