### ISSUE TITLE
后台执行groovy脚本写入数据库内容出错

### ISSUE THREAD

**Issue by yoqu** [hs-web/hsweb-framework#36]
使用版本: 2.2
根据文档,我在后台生成了一个`Owner`的模块,然后生成了一个脚本需要写入`s_modules`表中,但是我再后台管理界面无法执行,当我执行的时候报错,错误原因为:
```java
Caused by: groovy.lang.MissingPropertyException: No such property: database for class: Script6
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at Script6.run(Script6.groovy:4)
```
我的代码是:
```java
def owner_module= [u_id: 'owner', name: '管理员', uri: 'admin/owner/list.html', icon: '', parent_id: '-1', remark: '', status: 1, optional: '[{"id":"M","text":"菜单可见","checked":true},{"id":"import","text":"导入excel","checked":true},{"id":"export","text":"导出excel","checked":true},{"id":"R","text":"查询","checked":true},{"id":"C","text":"新增","checked":true},{"id":"U","text":"修改","checked":true},{"id":"D","text":"删除","checked":false}]', sort_index: 1];
database.getTable("s_modules").createInsert().value(owner_module).exec();
```
,是因为模板里面没有注入database变量吗? 然后我在启动的时候写了一个脚本可以执行,但是执行后无法在数据库表中看到数据插入了.

**Comment by zhou-hao** [comment]
你是在系统的脚本管理里执行的？这里默认没有注入database。你可以使用dynamicFormService.getDefaultDatabase 来获取。

**Comment by yoqu** [comment]
是否可以在代码中添加？我提一个pull request？

**Comment by zhou-hao** [comment]
@yoqu  你可以通过这个方式，编辑或者新增/resources/scripts/startup/init.groovy   内容为
```groovy
//设置一个全局变量
scriptEngine.addGlobalVariable([database:dynamicFormService.getDefaultDatabase()]);
```

**Comment by yoqu** [comment]
设置了全局变量,但是执行时候出现了表不存在的异常,是因为数据源不是配置文件里面的吗?
```Java
javax.script.ScriptException: java.lang.NullPointerException: 表不存在!
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:346)
	at org.codehaus.groovy.jsr223.GroovyCompiledScript.eval(GroovyCompiledScript.java:72)
	at org.hsweb.expands.script.engine.common.CommonScriptEngine.execute(CommonScriptEngine.java:109)
	at org.hsweb.web.service.impl.script.DynamicScriptExecuteServiceImpl.exec(DynamicScriptExecuteServiceImpl.java:73)
	at org.hsweb.web.service.impl.script.DynamicScriptExecuteServiceImpl.exec(DynamicScriptExecuteServiceImpl.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
还有在web-core中执行脚本没有捕获脚本执行的异常,我看日志也没有找到,稍微改了一下能找到异常原因,还请麻烦解决一下.谢谢

**Comment by zhou-hao** [comment]
@yoqu  尝试执行 `database.setAutoParse(true);`

**Comment by yoqu** [comment]
还是不行。通过debug默认我看了一下database这个里面的dataSource是我本地的库，但是不知道为啥不生效，我的spring-dev.yml配置文件：
```yml

hsweb:
    dynamic-datasource: #动态数据源配置
          url: jdbc:mysql://localhost:3306/hsweb??useUnicode=true&characterEncoding=utf-8
          username: root
          password:
          icatch:
            max-actives: 100
            output-dir: ./data/atomikos
            log_base_dir: ./data/atomikos
            default-jta-timeout: 300000
          type: mysql
    access-logger: on #开启访问日志

```
debug截图：
![image](https://cloud.githubusercontent.com/assets/10415165/26087891/3a7254a6-3a26-11e7-8758-60f98b7042de.png)。

注：项目我是可以跑起来的

**Comment by zhou-hao** [comment]
@yoqu 是执行了脚本 不生效?有没有报错?  怎么执行的,执行之后数据库里也没有? 有没有重新登录系统.

**Comment by yoqu** [comment]
报错原因就是表不存在，而我数据库中存在s_modules表，脚本是：
```groovy
//设置一个全局变量
scriptEngine.addGlobalVariable([database:dynamicFormService.getDefaultDatabase()]);
database.setAutoParse(true);
def module= [u_id: 'myTest', name: '测试', uri: 'admin/myTest/list.html', icon: '', parent_id: '-1', remark: '', status: 1, optional: '[{"id":"M","text":"菜单可见","checked":true},{"id":"import","text":"导入excel","checked":true},{"id":"export","text":"导出excel","checked":true},{"id":"R","text":"查询","checked":true},{"id":"C","text":"新增","checked":true},{"id":"U","text":"修改","checked":true},{"id":"D","text":"删除","checked":false}]', sort_index: 1];
database.getTable("s_modules").createInsert().value(module).exec();
```
在启动脚本里面这样写的
```groovy
println("=============安装数据库=====================")
try{
    scriptEngine.addGlobalVariable([database:dynamicFormService.getDefaultDatabase()]);
    def owner_module= [u_id: 'owner', name: '管理员', uri: 'admin/owner/list.html', icon: '', parent_id: '-1', remark: '', status: 1, optional: '[{"id":"M","text":"菜单可见","checked":true},{"id":"import","text":"导入excel","checked":true},{"id":"export","text":"导出excel","checked":true},{"id":"R","text":"查询","checked":true},{"id":"C","text":"新增","checked":true},{"id":"U","text":"修改","checked":true},{"id":"D","text":"删除","checked":false}]', sort_index: 1];
    database.setAutoParse(true);
    database.getTable("s_modules").createInsert().value(owner_module).exec();
}catch (Exception e){
    println("==============执行出现了异常,异常原因:"+e.getMessage());
}
```
启动时候报了表不存在。
然后刷新了数据库表也没有记录。已经重新登录了系统几次了。

**Comment by zhou-hao** [comment]
启动脚本改成
```groovy
println("=============安装数据库=====================")
try{
def database = dynamicFormService.getDefaultDatabase();
database.setAutoParse(true);

  //这个操作是设置变量,在其他脚本可以访问.
  scriptEngine.addGlobalVariable([database:database]);
 
    def owner_module= [u_id: 'owner', name: '管理员', uri: 'admin/owner/list.html', icon: '', parent_id: '-1', remark: '', status: 1, optional: '[{"id":"M","text":"菜单可见","checked":true},{"id":"import","text":"导入excel","checked":true},{"id":"export","text":"导出excel","checked":true},{"id":"R","text":"查询","checked":true},{"id":"C","text":"新增","checked":true},{"id":"U","text":"修改","checked":true},{"id":"D","text":"删除","checked":false}]', sort_index: 1];
    database.getTable("s_modules").createInsert().value(owner_module).exec();
}catch (Exception e){
    println("==============执行出现了异常,异常原因:"+e.getMessage());
}
```

**Comment by yoqu** [comment]
还是不行，最后我还是解决了。通过查看了下`SystemInitializeAutoConfiguration`类的代码，发现里面构造了一个 SimpleDatabase database ，但是我发现`DataBaseAutoConfiguration`类已经有一个生成bean的`RDBDatabase`了，请问这样做的原因是什么？我在`CoreAutoConfiguration`类中试了通过注解引入`DataBaseAutoConfiguration`类中的database，发现还是会报表不存在的错误，但是当我按照`SystemInitializeAutoConfiguration`类来构造database时候可以在脚本中写入内容。这两块是不是有问题？
重写的`CoreAutoConfiguration`，每次都给script注入database变量：

```java
package org.hsweb.web.core;

import org.hsweb.commons.StringUtils;
import org.hsweb.expands.script.engine.DynamicScriptEngine;
import org.hsweb.expands.script.engine.DynamicScriptEngineFactory;
import org.hsweb.ezorm.rdb.executor.SqlExecutor;
import org.hsweb.ezorm.rdb.meta.RDBDatabaseMetaData;
import org.hsweb.ezorm.rdb.meta.parser.H2TableMetaParser;
import org.hsweb.ezorm.rdb.meta.parser.MysqlTableMetaParser;
import org.hsweb.ezorm.rdb.meta.parser.OracleTableMetaParser;
import org.hsweb.ezorm.rdb.meta.parser.SqlServer2012TableMetaParser;
import org.hsweb.ezorm.rdb.render.dialect.H2RDBDatabaseMetaData;
import org.hsweb.ezorm.rdb.render.dialect.MSSQLRDBDatabaseMetaData;
import org.hsweb.ezorm.rdb.render.dialect.MysqlRDBDatabaseMetaData;
import org.hsweb.ezorm.rdb.render.dialect.OracleRDBDatabaseMetaData;
import org.hsweb.ezorm.rdb.simple.SimpleDatabase;
import org.hsweb.web.bean.po.user.User;
import org.hsweb.web.core.authorize.ExpressionScopeBean;
import org.hsweb.web.core.datasource.DataSourceHolder;
import org.hsweb.web.core.datasource.DatabaseType;
import org.hsweb.web.core.utils.WebUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.util.StreamUtils;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;
import java.io.IOException;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

@Configuration
@ComponentScan("org.hsweb.web.core")
public class CoreAutoConfiguration {

    protected Logger logger = LoggerFactory.getLogger(this.getClass());
    @Autowired
    DataSource dataSource;
    @Autowired
    SqlExecutor sqlExecutor;
    @Autowired(required = false)
    private Map<String, ExpressionScopeBean> expressionScopeBeanMap = new HashMap<>();
    private SimpleDatabase database;
    private String initializeScript = "classpath*:scripts/startup/*.";

    @PostConstruct
    public void init() throws SQLException {
        initScriptVariable();
        initScript();
    }

    /**
     * 初始化脚本参数.
     *
     * @throws SQLException
     */
    private void initScriptVariable() throws SQLException {
        DatabaseType type = DataSourceHolder.getDefaultDatabaseType();
        Connection connection = null;
        String jdbcUserName;
        try {
            connection = DataSourceHolder.getActiveSource().getConnection();
            jdbcUserName = connection.getMetaData().getUserName();
        } finally {
            if (null != connection) connection.close();
        }
        RDBDatabaseMetaData metaData;
        switch (type) {
            case oracle:
                metaData = new OracleRDBDatabaseMetaData();
                metaData.setParser(new OracleTableMetaParser(sqlExecutor));
                break;
            case mysql:
                metaData = new MysqlRDBDatabaseMetaData();
                metaData.setParser(new MysqlTableMetaParser(sqlExecutor));
                break;
            case jtds_sqlserver:
            case sqlserver:
                metaData = new MSSQLRDBDatabaseMetaData();
                metaData.setParser(new SqlServer2012TableMetaParser(sqlExecutor));
                break;
            default:
                h2:
                metaData = new H2RDBDatabaseMetaData();
                metaData.setParser(new H2TableMetaParser(sqlExecutor));
                break;
        }
        this.database = new SimpleDatabase(metaData, sqlExecutor);
        this.database.setAutoParse(true);
    }

    private void initScript() {
        Map<String, Object> vars = new HashMap<>(expressionScopeBeanMap);
        vars.put("LoginUser", (Supplier<User>) WebUtil::getLoginUser);
        vars.put("StringUtils", StringUtils.class);
        vars.put("User", User.class);

        initScript("js", vars);
        initScript("groovy", vars);
        initScript("java", vars);
        initScript("spel", vars);
        initScript("ognl", vars);
        initScript("ruby", vars);
        initScript("python", vars);
        //执行脚本
    }

    private void initScript(String language, Map<String, Object> vars) {
        try {
            DynamicScriptEngine engine = DynamicScriptEngineFactory.getEngine(language);
            if (engine == null) return;
            vars.put("logger", LoggerFactory.getLogger("org.hsweb.script.".concat(language)));
            vars.put("scriptEngine", engine);
            engine.addGlobalVariable(vars);
            Map<String, Object> scriptVars = new HashMap<>();
            scriptVars.put("database", database);
            Resource[] resources = new PathMatchingResourcePatternResolver().getResources(initializeScript.concat(language));
            for (Resource resource : resources) {
                String script = StreamUtils.copyToString(resource.getInputStream(), Charset.forName("utf-8"));
                engine.compile("__tmp", script);
                try {
                    engine.execute("__tmp", scriptVars);
                } catch (Exception e) {
                    logger.error(e.getMessage());
                } finally {
                    engine.remove("__tmp");
                }
            }
        } catch (NullPointerException e) {
            //
        } catch (IOException e) {
            logger.error("读取脚本文件失败", e);
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
    }

}
```

**Comment by zhou-hao** [comment]
系统安装时 database和 动态表单的database 可操作的表不一样.

**Comment by yoqu** [comment]
能请教一下动态表单操作的database是如何设计的？我看代码没有看太明白。

**Comment by zhou-hao** [comment]
@yoqu [hsweb-easy-orm](https://github.com/hs-web/hsweb-easy-orm)

**Comment by yoqu** [comment]
可以提供一下您的qq或者qq群吗？方便联系，对这个框架很有研究兴趣，希望能帮点忙
