### ISSUE TITLE
mac下运行报错

### ISSUE THREAD

**Issue by kings1990** [hs-web/hsweb-framework#73]
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:41) [classes/:na]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: format version ${project.version} error  
	at org.hswebframework.web.starter.init.SystemInitialize.initReadyToInstallDependencies(SystemInitialize.java:140) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:176) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	... 6 common frames omitted
Caused by: java.lang.UnsupportedOperationException: format version ${project.version} error  
	at org.hswebframework.web.starter.Version.setVersion(SystemVersion.java:209) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.hswebframework.web.starter.SystemVersion$Dependency.setVersion(SystemVersion.java:128) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.hswebframework.web.starter.SystemVersion$Dependency.fromMap(SystemVersion.java:162) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at org.hswebframework.web.starter.init.DependencyInstaller.setup(DependencyInstaller.java:35) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$11$\^eval\_.L:1(<eval>:280) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1) ~[na:na]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:421) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:514) ~[nashorn.jar:na]
	at org.hswebframework.expands.script.engine.common.CommonScriptEngine.execute(CommonScriptEngine.java:110) ~[hsweb-expands-script-3.0.0.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.initReadyToInstallDependencies(SystemInitialize.java:135) ~[hsweb-spring-boot-starter-3.0-SNAPSHOT.jar:na]
	... 9 common frames omitted

**Comment by zhou-hao** [comment]
先用mvn compile 编译一下试试
